--[[
* Macro editor catalog: retail + HorizonXI ability levels, weaponskills, spell omissions,
* blood pact status icons, and weaponskill tier labels. HzLimitedMode picks horizon vs retail.
]]--

local M = {};

M.retail = {
    abilitiesById = {
        [16] = { job = 1, level = 0, merit = false },
        [17] = { job = 2, level = 0, merit = false },
        [18] = { job = 3, level = 0, merit = false },
        [19] = { job = 4, level = 0, merit = false },
        [20] = { job = 5, level = 0, merit = false },
        [21] = { job = 6, level = 0, merit = false },
        [22] = { job = 7, level = 0, merit = false },
        [23] = { job = 8, level = 0, merit = false },
        [24] = { job = 9, level = 0, merit = false },
        [25] = { job = 10, level = 0, merit = false },
        [26] = { job = 11, level = 0, merit = false },
        [27] = { job = 12, level = 0, merit = false },
        [28] = { job = 13, level = 0, merit = false },
        [29] = { job = 14, level = 0, merit = false },
        [30] = { job = 15, level = 0, merit = false },
        [31] = { job = 1, level = 15, merit = true },
        [32] = { job = 1, level = 35, merit = true },
        [33] = { job = 1, level = 25, merit = true },
        [34] = { job = 1, level = 45, merit = true },
        [35] = { job = 1, level = 5, merit = false },
        [36] = { job = 2, level = 25, merit = true },
        [37] = { job = 2, level = 15, merit = true },
        [38] = { job = 2, level = 35, merit = true },
        [39] = { job = 2, level = 5, merit = false },
        [40] = { job = 2, level = 45, merit = false },
        [41] = { job = 6, level = 5, merit = false },
        [42] = { job = 6, level = 25, merit = true },
        [43] = { job = 6, level = 45, merit = true },
        [44] = { job = 6, level = 15, merit = true },
        [45] = { job = 6, level = 35, merit = false },
        [46] = { job = 7, level = 15, merit = true },
        [47] = { job = 7, level = 5, merit = true },
        [48] = { job = 7, level = 30, merit = true },
        [49] = { job = 8, level = 30, merit = true },
        [50] = { job = 8, level = 5, merit = true },
        [51] = { job = 8, level = 15, merit = true },
        [52] = { job = 9, level = 1, merit = false },
        [53] = { job = 9, level = 10, merit = false },
        [54] = { job = 9, level = 30, merit = true },
        [55] = { job = 9, level = 1, merit = false },
        [56] = { job = 11, level = 10, merit = true },
        [57] = { job = 11, level = 40, merit = false },
        [58] = { job = 11, level = 20, merit = true },
        [59] = { job = 11, level = 1, merit = true },
        [60] = { job = 11, level = 30, merit = false },
        [61] = { job = 14, level = 1, merit = false },
        [62] = { job = 12, level = 15, merit = true },
        [63] = { job = 12, level = 30, merit = true },
        [64] = { job = 12, level = 5, merit = true },
        [65] = { job = 14, level = 5, merit = true },
        [66] = { job = 14, level = 10, merit = true },
        [67] = { job = 14, level = 35, merit = true },
        [68] = { job = 14, level = 50, merit = true },
        [69] = { job = 9, level = 1, merit = false },
        [70] = { job = 9, level = 10, merit = false },
        [71] = { job = 9, level = 35, merit = false },
        [72] = { job = 9, level = 25, merit = true },
        [73] = { job = 9, level = 15, merit = false },
        [74] = { job = 3, level = 15, merit = true },
        [75] = { job = 4, level = 15, merit = true },
        [76] = { job = 6, level = 30, merit = true },
        [77] = { job = 8, level = 20, merit = false },
        [78] = { job = 9, level = 12, merit = true },
        [79] = { job = 7, level = 35, merit = false },
        [80] = { job = 14, level = 25, merit = true },
        [81] = { job = 0, level = 0, merit = false },
        [82] = { job = 2, level = 41, merit = false },
        [83] = { job = 5, level = 40, merit = true },
        [84] = { job = 6, level = 65, merit = false },
        [85] = { job = 9, level = 23, merit = true },
        [86] = { job = 11, level = 51, merit = true },
        [87] = { job = 14, level = 1, merit = false },
        [88] = { job = 15, level = 1, merit = false },
        [89] = { job = 15, level = 1, merit = false },
        [90] = { job = 15, level = 1, merit = false },
        [91] = { job = 15, level = 1, merit = false },
        [92] = { job = 7, level = 62, merit = true },
        [93] = { job = 16, level = 0, merit = false },
        [94] = { job = 16, level = 40, merit = true },
        [95] = { job = 16, level = 25, merit = true },
        [96] = { job = 17, level = 0, merit = false },
        [97] = { job = 17, level = 5, merit = true },
        [98] = { job = 17, level = 49, merit = false },
        [99] = { job = 17, level = 31, merit = false },
        [100] = { job = 17, level = 20, merit = false },
        [101] = { job = 17, level = 58, merit = false },
        [102] = { job = 17, level = 46, merit = false },
        [103] = { job = 17, level = 43, merit = false },
        [104] = { job = 17, level = 55, merit = false },
        [105] = { job = 17, level = 14, merit = false },
        [106] = { job = 17, level = 34, merit = false },
        [107] = { job = 17, level = 26, merit = false },
        [108] = { job = 17, level = 11, merit = false },
        [109] = { job = 17, level = 34, merit = false },
        [110] = { job = 17, level = 8, merit = false },
        [111] = { job = 17, level = 23, merit = false },
        [112] = { job = 17, level = 40, merit = false },
        [113] = { job = 17, level = 17, merit = false },
        [114] = { job = 17, level = 5, merit = false },
        [115] = { job = 17, level = 52, merit = false },
        [116] = { job = 17, level = 61, merit = false },
        [117] = { job = 17, level = 64, merit = false },
        [118] = { job = 17, level = 76, merit = false },
        [119] = { job = 17, level = 79, merit = false },
        [120] = { job = 17, level = 81, merit = false },
        [121] = { job = 17, level = 83, merit = false },
        [122] = { job = 17, level = 86, merit = false },
        [123] = { job = 17, level = 5, merit = false },
        [124] = { job = 17, level = 40, merit = true },
        [125] = { job = 17, level = 40, merit = true },
        [126] = { job = 17, level = 40, merit = true },
        [127] = { job = 17, level = 40, merit = true },
        [128] = { job = 17, level = 40, merit = true },
        [129] = { job = 17, level = 40, merit = true },
        [130] = { job = 17, level = 40, merit = true },
        [131] = { job = 17, level = 40, merit = true },
        [132] = { job = 17, level = 40, merit = true },
        [133] = { job = 17, level = 50, merit = true },
        [135] = { job = 18, level = 0, merit = false },
        [136] = { job = 18, level = 1, merit = true },
        [137] = { job = 18, level = 15, merit = true },
        [138] = { job = 18, level = 1, merit = false },
        [139] = { job = 18, level = 1, merit = false },
        [140] = { job = 18, level = 10, merit = false },
        [141] = { job = 18, level = 1, merit = false },
        [142] = { job = 18, level = 1, merit = false },
        [143] = { job = 18, level = 1, merit = false },
        [144] = { job = 18, level = 1, merit = false },
        [145] = { job = 18, level = 1, merit = false },
        [146] = { job = 18, level = 1, merit = false },
        [147] = { job = 18, level = 1, merit = false },
        [148] = { job = 18, level = 1, merit = false },
        [149] = { job = 1, level = 75, merit = true },
        [150] = { job = 1, level = 75, merit = true },
        [151] = { job = 2, level = 75, merit = true },
        [152] = { job = 2, level = 75, merit = true },
        [153] = { job = 3, level = 75, merit = true },
        [154] = { job = 3, level = 75, merit = true },
        [155] = { job = 6, level = 75, merit = true },
        [156] = { job = 6, level = 75, merit = true },
        [157] = { job = 7, level = 75, merit = true },
        [158] = { job = 7, level = 75, merit = true },
        [159] = { job = 8, level = 75, merit = true },
        [160] = { job = 8, level = 75, merit = true },
        [161] = { job = 9, level = 75, merit = true },
        [162] = { job = 9, level = 75, merit = true },
        [163] = { job = 10, level = 75, merit = true },
        [164] = { job = 10, level = 75, merit = true },
        [165] = { job = 11, level = 75, merit = true },
        [166] = { job = 11, level = 75, merit = true },
        [167] = { job = 12, level = 75, merit = true },
        [168] = { job = 12, level = 75, merit = true },
        [169] = { job = 14, level = 75, merit = true },
        [170] = { job = 14, level = 75, merit = true },
        [171] = { job = 13, level = 75, merit = true },
        [172] = { job = 15, level = 1, merit = false },
        [173] = { job = 12, level = 25, merit = false },
        [174] = { job = 12, level = 35, merit = false },
        [175] = { job = 16, level = 75, merit = true },
        [176] = { job = 16, level = 75, merit = true },
        [177] = { job = 17, level = 75, merit = true },
        [178] = { job = 17, level = 75, merit = true },
        [179] = { job = 18, level = 75, merit = true },
        [180] = { job = 18, level = 75, merit = true },
        [181] = { job = 19, level = 0, merit = false },
        [182] = { job = 19, level = 5, merit = false },
        [183] = { job = 19, level = 15, merit = false },
        [184] = { job = 19, level = 5, merit = false },
        [185] = { job = 19, level = 35, merit = false },
        [186] = { job = 19, level = 65, merit = false },
        [187] = { job = 19, level = 25, merit = false },
        [188] = { job = 19, level = 60, merit = false },
        [189] = { job = 19, level = 45, merit = false },
        [190] = { job = 19, level = 15, merit = false },
        [191] = { job = 19, level = 30, merit = false },
        [192] = { job = 19, level = 45, merit = false },
        [193] = { job = 19, level = 70, merit = false },
        [194] = { job = 19, level = 35, merit = false },
        [195] = { job = 19, level = 25, merit = false },
        [196] = { job = 19, level = 25, merit = false },
        [197] = { job = 19, level = 55, merit = false },
        [198] = { job = 19, level = 25, merit = false },
        [199] = { job = 19, level = 20, merit = false },
        [200] = { job = 19, level = 20, merit = false },
        [201] = { job = 19, level = 20, merit = false },
        [202] = { job = 19, level = 30, merit = false },
        [203] = { job = 19, level = 40, merit = false },
        [204] = { job = 19, level = 20, merit = false },
        [205] = { job = 19, level = 30, merit = false },
        [206] = { job = 19, level = 40, merit = false },
        [207] = { job = 19, level = 45, merit = false },
        [208] = { job = 19, level = 50, merit = false },
        [209] = { job = 19, level = 60, merit = false },
        [210] = { job = 20, level = 0, merit = false },
        [211] = { job = 20, level = 10, merit = true },
        [212] = { job = 20, level = 10, merit = true },
        [213] = { job = 19, level = 40, merit = false },
        [214] = { job = 20, level = 65, merit = false },
        [215] = { job = 20, level = 10, merit = false },
        [216] = { job = 20, level = 25, merit = false },
        [217] = { job = 20, level = 55, merit = false },
        [218] = { job = 20, level = 40, merit = false },
        [219] = { job = 20, level = 10, merit = false },
        [220] = { job = 20, level = 25, merit = false },
        [221] = { job = 20, level = 55, merit = false },
        [222] = { job = 20, level = 40, merit = false },
        [223] = { job = 20, level = 10, merit = false },
        [224] = { job = 11, level = 45, merit = false },
        [225] = { job = 9, level = 45, merit = false },
        [226] = { job = 1, level = 60, merit = false },
        [227] = { job = 2, level = 65, merit = false },
        [228] = { job = 6, level = 77, merit = false },
        [229] = { job = 10, level = 20, merit = false },
        [230] = { job = 12, level = 40, merit = false },
        [232] = { job = 15, level = 50, merit = false },
        [233] = { job = 20, level = 35, merit = false },
        [234] = { job = 20, level = 10, merit = false },
        [235] = { job = 20, level = 30, merit = false },
        [236] = { job = 6, level = 65, merit = false },
        [237] = { job = 19, level = 75, merit = true },
        [238] = { job = 19, level = 75, merit = true },
        [239] = { job = 19, level = 75, merit = true },
        [240] = { job = 20, level = 75, merit = true },
        [241] = { job = 20, level = 75, merit = true },
        [242] = { job = 20, level = 75, merit = true },
        [243] = { job = 20, level = 75, merit = true },
        [244] = { job = 20, level = 75, merit = true },
        [245] = { job = 3, level = 40, merit = false },
        [246] = { job = 3, level = 40, merit = false },
        [247] = { job = 5, level = 50, merit = false },
        [248] = { job = 13, level = 40, merit = false },
        [249] = { job = 13, level = 40, merit = false },
        [250] = { job = 15, level = 55, merit = false },
        [251] = { job = 9, level = 25, merit = true },
        [252] = { job = 1, level = 77, merit = false },
        [253] = { job = 2, level = 79, merit = false },
        [254] = { job = 4, level = 76, merit = false },
        [255] = { job = 7, level = 78, merit = false },
        [256] = { job = 8, level = 78, merit = false },
        [257] = { job = 11, level = 79, merit = false },
        [258] = { job = 12, level = 77, merit = false },
        [259] = { job = 13, level = 77, merit = false },
        [260] = { job = 14, level = 77, merit = true },
        [261] = { job = 19, level = 77, merit = false },
        [262] = { job = 19, level = 78, merit = false },
        [263] = { job = 19, level = 80, merit = false },
        [264] = { job = 19, level = 80, merit = false },
        [265] = { job = 20, level = 76, merit = false },
        [266] = { job = 18, level = 79, merit = false },
        [267] = { job = 1, level = 87, merit = false },
        [269] = { job = 2, level = 88, merit = false },
        [270] = { job = 3, level = 83, merit = false },
        [271] = { job = 3, level = 95, merit = false },
        [272] = { job = 4, level = 87, merit = false },
        [273] = { job = 4, level = 95, merit = false },
        [274] = { job = 5, level = 83, merit = false },
        [275] = { job = 5, level = 95, merit = false },
        [276] = { job = 6, level = 87, merit = false },
        [277] = { job = 7, level = 87, merit = false },
        [278] = { job = 7, level = 95, merit = false },
        [279] = { job = 8, level = 87, merit = false },
        [280] = { job = 8, level = 95, merit = false },
        [281] = { job = 9, level = 83, merit = false },
        [282] = { job = 9, level = 93, merit = false },
        [283] = { job = 10, level = 83, merit = false },
        [284] = { job = 10, level = 95, merit = false },
        [285] = { job = 11, level = 87, merit = false },
        [286] = { job = 11, level = 95, merit = false },
        [287] = { job = 12, level = 87, merit = false },
        [288] = { job = 12, level = 95, merit = false },
        [291] = { job = 13, level = 95, merit = false },
        [292] = { job = 14, level = 87, merit = false },
        [293] = { job = 14, level = 85, merit = true },
        [295] = { job = 14, level = 95, merit = false },
        [296] = { job = 15, level = 87, merit = false },
        [297] = { job = 16, level = 83, merit = false },
        [298] = { job = 16, level = 95, merit = false },
        [301] = { job = 17, level = 87, merit = false },
        [302] = { job = 17, level = 89, merit = false },
        [303] = { job = 17, level = 92, merit = false },
        [304] = { job = 17, level = 95, merit = false },
        [305] = { job = 17, level = 97, merit = false },
        [309] = { job = 18, level = 95, merit = false },
        [310] = { job = 18, level = 5, merit = false },
        [311] = { job = 19, level = 87, merit = false },
        [312] = { job = 19, level = 83, merit = false },
        [313] = { job = 19, level = 89, merit = false },
        [314] = { job = 19, level = 93, merit = false },
        [316] = { job = 20, level = 87, merit = false },
        [317] = { job = 20, level = 87, merit = false },
        [318] = { job = 14, level = 90, merit = false },
        [319] = { job = 14, level = 90, merit = false },
        [320] = { job = 12, level = 65, merit = false },
        [321] = { job = 6, level = 93, merit = false },
        [322] = { job = 18, level = 30, merit = true },
        [323] = { job = 1, level = 96, merit = false },
        [324] = { job = 2, level = 96, merit = false },
        [325] = { job = 3, level = 96, merit = false },
        [326] = { job = 4, level = 96, merit = false },
        [327] = { job = 5, level = 96, merit = false },
        [328] = { job = 6, level = 96, merit = false },
        [329] = { job = 7, level = 96, merit = false },
        [330] = { job = 8, level = 96, merit = false },
        [331] = { job = 9, level = 96, merit = false },
        [332] = { job = 10, level = 96, merit = false },
        [333] = { job = 11, level = 96, merit = false },
        [334] = { job = 12, level = 96, merit = false },
        [335] = { job = 13, level = 96, merit = false },
        [336] = { job = 14, level = 96, merit = false },
        [337] = { job = 15, level = 96, merit = false },
        [338] = { job = 16, level = 96, merit = false },
        [339] = { job = 17, level = 96, merit = false },
        [340] = { job = 18, level = 96, merit = false },
        [341] = { job = 19, level = 96, merit = false },
        [342] = { job = 20, level = 96, merit = false },
        [343] = { job = 21, level = 1, merit = false },
        [344] = { job = 22, level = 25, merit = false },
        [345] = { job = 21, level = 5, merit = false },
        [346] = { job = 21, level = 25, merit = true },
        [347] = { job = 21, level = 25, merit = true },
        [348] = { job = 21, level = 40, merit = false },
        [349] = { job = 21, level = 50, merit = true },
        [350] = { job = 21, level = 60, merit = true },
        [351] = { job = 21, level = 70, merit = true },
        [352] = { job = 21, level = 80, merit = false },
        [353] = { job = 21, level = 90, merit = false },
        [354] = { job = 21, level = 75, merit = true },
        [355] = { job = 21, level = 75, merit = true },
        [356] = { job = 22, level = 0, merit = false },
        [357] = { job = 22, level = 5, merit = false },
        [358] = { job = 22, level = 5, merit = false },
        [359] = { job = 22, level = 5, merit = false },
        [360] = { job = 22, level = 5, merit = false },
        [361] = { job = 22, level = 5, merit = false },
        [362] = { job = 22, level = 5, merit = false },
        [363] = { job = 22, level = 5, merit = false },
        [364] = { job = 22, level = 5, merit = false },
        [365] = { job = 22, level = 5, merit = false },
        [366] = { job = 22, level = 10, merit = false },
        [367] = { job = 22, level = 20, merit = false },
        [368] = { job = 22, level = 25, merit = true },
        [369] = { job = 22, level = 40, merit = false },
        [370] = { job = 22, level = 60, merit = false },
        [371] = { job = 22, level = 50, merit = false },
        [372] = { job = 22, level = 70, merit = true },
        [373] = { job = 22, level = 85, merit = false },
        [374] = { job = 22, level = 95, merit = false },
        [375] = { job = 22, level = 75, merit = true },
        [376] = { job = 22, level = 75, merit = true },
        [377] = { job = 21, level = 96, merit = false },
        [378] = { job = 22, level = 96, merit = false },
        [379] = { job = 22, level = 1, merit = false },
        [380] = { job = 22, level = 1, merit = false },
        [381] = { job = 19, level = 70, merit = false },
        [382] = { job = 23, level = 1, merit = false },
        [383] = { job = 22, level = 65, merit = false },
        [384] = { job = 19, level = 50, merit = false },
        [385] = { job = 15, level = 70, merit = false },
        [386] = { job = 21, level = 75, merit = false },
        [387] = { job = 9, level = 23, merit = true },
        [388] = { job = 4, level = 85, merit = false },
        [389] = { job = 8, level = 55, merit = false },
        [390] = { job = 17, level = 67, merit = false },
        [391] = { job = 17, level = 70, merit = false },
        [392] = { job = 17, level = 95, merit = false },
        [393] = { job = 14, level = 65, merit = false },
        [394] = { job = 7, level = 70, merit = false },
        [512] = { job = 15, level = 1, merit = false },
        [513] = { job = 15, level = 5, merit = false },
        [514] = { job = 15, level = 24, merit = false },
        [515] = { job = 15, level = 44, merit = false },
        [516] = { job = 15, level = 55, merit = false },
        [517] = { job = 15, level = 65, merit = false },
        [518] = { job = 15, level = 1, merit = false },
        [519] = { job = 15, level = 76, merit = false },
        [520] = { job = 15, level = 94, merit = false },
        [521] = { job = 15, level = 1, merit = false },
        [522] = { job = 15, level = 25, merit = false },
        [523] = { job = 15, level = 55, merit = false },
        [524] = { job = 15, level = 75, merit = false },
        [525] = { job = 15, level = 15, merit = false },
        [526] = { job = 15, level = 30, merit = false },
        [527] = { job = 15, level = 1, merit = false },
        [528] = { job = 15, level = 5, merit = false },
        [529] = { job = 15, level = 10, merit = false },
        [530] = { job = 15, level = 21, merit = false },
        [531] = { job = 15, level = 32, merit = false },
        [532] = { job = 15, level = 43, merit = false },
        [533] = { job = 15, level = 54, merit = false },
        [534] = { job = 15, level = 65, merit = false },
        [536] = { job = 15, level = 1, merit = false },
        [537] = { job = 15, level = 78, merit = false },
        [538] = { job = 15, level = 96, merit = false },
        [539] = { job = 15, level = 99, merit = false },
        [544] = { job = 15, level = 1, merit = false },
        [545] = { job = 15, level = 10, merit = false },
        [546] = { job = 15, level = 23, merit = false },
        [547] = { job = 15, level = 30, merit = false },
        [548] = { job = 15, level = 38, merit = false },
        [549] = { job = 15, level = 60, merit = false },
        [550] = { job = 15, level = 70, merit = false },
        [551] = { job = 15, level = 75, merit = true },
        [552] = { job = 15, level = 1, merit = false },
        [553] = { job = 15, level = 88, merit = false },
        [554] = { job = 15, level = 99, merit = false },
        [560] = { job = 15, level = 1, merit = false },
        [561] = { job = 15, level = 10, merit = false },
        [562] = { job = 15, level = 21, merit = false },
        [563] = { job = 15, level = 35, merit = false },
        [564] = { job = 15, level = 46, merit = false },
        [565] = { job = 15, level = 60, merit = false },
        [566] = { job = 15, level = 70, merit = false },
        [567] = { job = 15, level = 75, merit = true },
        [568] = { job = 15, level = 1, merit = false },
        [569] = { job = 15, level = 82, merit = false },
        [570] = { job = 15, level = 99, merit = false },
        [576] = { job = 15, level = 1, merit = false },
        [577] = { job = 15, level = 10, merit = false },
        [578] = { job = 15, level = 26, merit = false },
        [579] = { job = 15, level = 47, merit = false },
        [580] = { job = 15, level = 33, merit = false },
        [581] = { job = 15, level = 60, merit = false },
        [582] = { job = 15, level = 70, merit = false },
        [583] = { job = 15, level = 75, merit = true },
        [584] = { job = 15, level = 1, merit = false },
        [585] = { job = 15, level = 84, merit = false },
        [586] = { job = 15, level = 99, merit = false },
        [592] = { job = 15, level = 1, merit = false },
        [593] = { job = 15, level = 10, merit = false },
        [594] = { job = 15, level = 36, merit = false },
        [595] = { job = 15, level = 48, merit = false },
        [596] = { job = 15, level = 25, merit = false },
        [597] = { job = 15, level = 60, merit = false },
        [598] = { job = 15, level = 70, merit = false },
        [599] = { job = 15, level = 75, merit = true },
        [600] = { job = 15, level = 1, merit = false },
        [601] = { job = 15, level = 86, merit = false },
        [602] = { job = 15, level = 99, merit = false },
        [608] = { job = 15, level = 1, merit = false },
        [609] = { job = 15, level = 10, merit = false },
        [610] = { job = 15, level = 28, merit = false },
        [611] = { job = 15, level = 39, merit = false },
        [612] = { job = 15, level = 50, merit = false },
        [613] = { job = 15, level = 60, merit = false },
        [614] = { job = 15, level = 70, merit = false },
        [615] = { job = 15, level = 75, merit = true },
        [616] = { job = 15, level = 1, merit = false },
        [617] = { job = 15, level = 90, merit = false },
        [618] = { job = 15, level = 99, merit = false },
        [624] = { job = 15, level = 1, merit = false },
        [625] = { job = 15, level = 10, merit = false },
        [626] = { job = 15, level = 31, merit = false },
        [627] = { job = 15, level = 19, merit = false },
        [628] = { job = 15, level = 42, merit = false },
        [629] = { job = 15, level = 60, merit = false },
        [630] = { job = 15, level = 70, merit = false },
        [631] = { job = 15, level = 75, merit = true },
        [632] = { job = 15, level = 1, merit = false },
        [633] = { job = 15, level = 92, merit = false },
        [634] = { job = 15, level = 99, merit = false },
        [639] = { job = 0, level = 80, merit = false },
        [640] = { job = 0, level = 1, merit = false },
        [641] = { job = 0, level = 20, merit = false },
        [642] = { job = 0, level = 40, merit = false },
        [643] = { job = 0, level = 1, merit = false },
        [644] = { job = 0, level = 20, merit = false },
        [645] = { job = 0, level = 40, merit = false },
        [646] = { job = 0, level = 1, merit = false },
        [647] = { job = 0, level = 1, merit = false },
        [648] = { job = 0, level = 1, merit = false },
        [649] = { job = 0, level = 1, merit = false },
        [650] = { job = 0, level = 1, merit = false },
        [651] = { job = 0, level = 1, merit = false },
        [652] = { job = 0, level = 50, merit = false },
        [653] = { job = 0, level = 60, merit = false },
        [654] = { job = 0, level = 80, merit = false },
        [656] = { job = 15, level = 1, merit = false },
        [657] = { job = 15, level = 20, merit = false },
        [658] = { job = 15, level = 29, merit = false },
        [659] = { job = 15, level = 37, merit = false },
        [660] = { job = 15, level = 49, merit = false },
        [661] = { job = 15, level = 56, merit = false },
        [662] = { job = 15, level = 65, merit = false },
        [663] = { job = 22, level = 1, merit = false },
        [664] = { job = 15, level = 1, merit = false },
        [665] = { job = 15, level = 80, merit = false },
        [666] = { job = 15, level = 98, merit = false },
        [667] = { job = 15, level = 99, merit = false },
        [668] = { job = 22, level = 1, merit = false },
        [669] = { job = 22, level = 1, merit = false },
        [670] = { job = 22, level = 1, merit = false },
        [671] = { job = 22, level = 1, merit = false },
        [672] = { job = 9, level = 25, merit = false },
        [673] = { job = 9, level = 25, merit = false },
        [674] = { job = 9, level = 25, merit = false },
        [675] = { job = 9, level = 25, merit = false },
        [676] = { job = 9, level = 25, merit = false },
        [677] = { job = 9, level = 25, merit = false },
        [678] = { job = 9, level = 25, merit = false },
        [679] = { job = 9, level = 25, merit = false },
        [680] = { job = 9, level = 25, merit = false },
        [681] = { job = 9, level = 25, merit = false },
        [682] = { job = 9, level = 25, merit = false },
        [683] = { job = 9, level = 25, merit = false },
        [684] = { job = 9, level = 25, merit = false },
        [685] = { job = 9, level = 25, merit = false },
        [686] = { job = 9, level = 25, merit = false },
        [687] = { job = 9, level = 25, merit = false },
        [688] = { job = 9, level = 25, merit = false },
        [689] = { job = 9, level = 25, merit = false },
        [690] = { job = 9, level = 25, merit = false },
        [691] = { job = 9, level = 25, merit = false },
        [692] = { job = 9, level = 25, merit = false },
        [693] = { job = 9, level = 25, merit = false },
        [694] = { job = 9, level = 25, merit = false },
        [695] = { job = 9, level = 25, merit = false },
        [696] = { job = 9, level = 25, merit = false },
        [697] = { job = 9, level = 25, merit = false },
        [698] = { job = 9, level = 25, merit = false },
        [699] = { job = 9, level = 25, merit = false },
        [700] = { job = 9, level = 25, merit = false },
        [701] = { job = 9, level = 25, merit = false },
        [702] = { job = 9, level = 25, merit = false },
        [703] = { job = 9, level = 25, merit = false },
        [704] = { job = 9, level = 25, merit = false },
        [705] = { job = 9, level = 25, merit = false },
        [706] = { job = 9, level = 25, merit = false },
        [707] = { job = 9, level = 25, merit = false },
        [708] = { job = 9, level = 25, merit = false },
        [709] = { job = 9, level = 25, merit = false },
        [710] = { job = 9, level = 25, merit = false },
        [711] = { job = 9, level = 25, merit = false },
        [712] = { job = 9, level = 25, merit = false },
        [713] = { job = 9, level = 25, merit = false },
        [714] = { job = 9, level = 25, merit = false },
        [715] = { job = 9, level = 25, merit = false },
        [716] = { job = 9, level = 25, merit = false },
        [717] = { job = 9, level = 25, merit = false },
        [718] = { job = 9, level = 25, merit = false },
        [719] = { job = 9, level = 25, merit = false },
        [720] = { job = 9, level = 25, merit = false },
        [721] = { job = 9, level = 25, merit = false },
        [722] = { job = 9, level = 25, merit = false },
        [723] = { job = 9, level = 25, merit = false },
        [724] = { job = 9, level = 25, merit = false },
        [725] = { job = 9, level = 25, merit = false },
        [726] = { job = 9, level = 25, merit = false },
        [727] = { job = 9, level = 25, merit = false },
        [728] = { job = 9, level = 25, merit = false },
        [729] = { job = 9, level = 25, merit = false },
        [730] = { job = 9, level = 25, merit = false },
        [731] = { job = 9, level = 25, merit = false },
        [732] = { job = 9, level = 25, merit = false },
        [733] = { job = 9, level = 25, merit = false },
        [734] = { job = 9, level = 25, merit = false },
        [735] = { job = 9, level = 25, merit = false },
        [736] = { job = 9, level = 25, merit = false },
        [737] = { job = 9, level = 25, merit = false },
        [738] = { job = 9, level = 25, merit = false },
        [740] = { job = 10, level = 25, merit = false },
        [741] = { job = 10, level = 25, merit = false },
        [743] = { job = 9, level = 26, merit = false },
        [744] = { job = 9, level = 26, merit = false },
        [745] = { job = 9, level = 25, merit = false },
        [746] = { job = 9, level = 26, merit = false },
        [747] = { job = 9, level = 25, merit = false },
        [748] = { job = 9, level = 25, merit = false },
        [749] = { job = 9, level = 25, merit = false },
        [750] = { job = 9, level = 25, merit = false },
        [751] = { job = 9, level = 25, merit = false },
        [752] = { job = 9, level = 25, merit = false },
        [753] = { job = 9, level = 25, merit = false },
        [754] = { job = 9, level = 25, merit = false },
        [755] = { job = 9, level = 25, merit = false },
        [756] = { job = 9, level = 25, merit = false },
        [757] = { job = 9, level = 25, merit = false },
        [758] = { job = 9, level = 25, merit = false },
        [759] = { job = 9, level = 25, merit = false },
        [760] = { job = 9, level = 25, merit = false },
        [761] = { job = 9, level = 25, merit = false },
        [762] = { job = 9, level = 25, merit = false },
        [763] = { job = 9, level = 25, merit = false },
        [764] = { job = 9, level = 25, merit = false },
        [765] = { job = 9, level = 25, merit = false },
        [766] = { job = 9, level = 25, merit = false },
        [767] = { job = 9, level = 25, merit = false },
        [768] = { job = 9, level = 25, merit = false },
        [769] = { job = 9, level = 25, merit = false },
        [770] = { job = 9, level = 25, merit = false },
        [771] = { job = 9, level = 25, merit = false },
        [772] = { job = 9, level = 25, merit = false },
        [773] = { job = 15, level = 99, merit = false },
        [774] = { job = 9, level = 25, merit = false },
        [775] = { job = 9, level = 25, merit = false },
        [776] = { job = 9, level = 25, merit = false },
        [777] = { job = 9, level = 25, merit = false },
        [778] = { job = 9, level = 25, merit = false },
        [779] = { job = 9, level = 25, merit = false },
        [780] = { job = 22, level = 1, merit = false },
        [781] = { job = 9, level = 25, merit = false },
        [782] = { job = 9, level = 25, merit = false },
        [786] = { job = 22, level = 1, merit = false },
        [787] = { job = 22, level = 1, merit = false },
        [960] = { job = 15, level = 1, merit = false },
        [961] = { job = 15, level = 1, merit = false },
        [962] = { job = 15, level = 1, merit = false },
        [963] = { job = 15, level = 1, merit = false },
        [964] = { job = 15, level = 25, merit = false },
        [965] = { job = 15, level = 1, merit = false },
        [966] = { job = 15, level = 1, merit = false },
        [967] = { job = 15, level = 65, merit = false },
        [968] = { job = 15, level = 75, merit = false },
        [970] = { job = 15, level = 99, merit = false },
    },
    weaponskillsByName = {
        ['Arching Arrow'] = { weapon = 'Archery', skill = 225 },
        ['Armor Break'] = { weapon = 'Great Axe', skill = 100 },
        ['Asuran Fists'] = { weapon = 'Hand-to-Hand', skill = 250 },
        ['Avalanche Axe'] = { weapon = 'Axe', skill = 100 },
        ['Backhand Blow'] = { weapon = 'Hand-to-Hand', skill = 100 },
        ['Black Halo'] = { weapon = 'Club', skill = 230 },
        ['Blade: Chi'] = { weapon = 'Katana', skill = 150 },
        ['Blade: Ei'] = { weapon = 'Katana', skill = 175 },
        ['Blade: Jin'] = { weapon = 'Katana', skill = 200 },
        ['Blade: Ku'] = { weapon = 'Katana', skill = 250 },
        ['Blade: Metsu'] = { weapon = 'Katana', skill = 0, relic = true },
        ['Blade: Retsu'] = { weapon = 'Katana', skill = 30 },
        ['Blade: Rin'] = { weapon = 'Katana', skill = 5 },
        ['Blade: Teki'] = { weapon = 'Katana', skill = 70 },
        ['Blade: Ten'] = { weapon = 'Katana', skill = 225 },
        ['Blade: To'] = { weapon = 'Katana', skill = 100 },
        ['Blast Arrow'] = { weapon = 'Archery', skill = 200 },
        ['Blast Shot'] = { weapon = 'Marksmanship', skill = 200 },
        ['Brainshaker'] = { weapon = 'Club', skill = 70 },
        ['Burning Blade'] = { weapon = 'Sword', skill = 30 },
        ['Calamity'] = { weapon = 'Axe', skill = 200 },
        ['Catastrophe'] = { weapon = 'Scythe', skill = 0, relic = true },
        ['Circle Blade'] = { weapon = 'Sword', skill = 150 },
        ['Combo'] = { weapon = 'Hand-to-Hand', skill = 5 },
        ['Coronach'] = { weapon = 'Marksmanship', skill = 0, relic = true },
        ['Crescent Moon'] = { weapon = 'Great Sword', skill = 175 },
        ['Cross Reaper'] = { weapon = 'Scythe', skill = 225 },
        ['Cyclone'] = { weapon = 'Dagger', skill = 125 },
        ['Dancing Edge'] = { weapon = 'Dagger', skill = 200 },
        ['Dark Harvest'] = { weapon = 'Scythe', skill = 30 },
        ['Decimation'] = { weapon = 'Axe', skill = 240 },
        ['Detonator'] = { weapon = 'Marksmanship', skill = 250 },
        ['Double Thrust'] = { weapon = 'Polearm', skill = 5 },
        ['Dragon Kick'] = { weapon = 'Hand-to-Hand', skill = 225 },
        ['Dulling Arrow'] = { weapon = 'Archery', skill = 80 },
        ['Earth Crusher'] = { weapon = 'Staff', skill = 70 },
        ['Empyreal Arrow'] = { weapon = 'Archery', skill = 250 },
        ['Energy Drain'] = { weapon = 'Dagger', skill = 175 },
        ['Energy Steal'] = { weapon = 'Dagger', skill = 150 },
        ['Evisceration'] = { weapon = 'Dagger', skill = 230 },
        ['Fast Blade'] = { weapon = 'Sword', skill = 5 },
        ['Final Heaven'] = { weapon = 'Hand-to-Hand', skill = 0, relic = true },
        ['Flaming Arrow'] = { weapon = 'Archery', skill = 5 },
        ['Flat Blade'] = { weapon = 'Sword', skill = 75 },
        ['Freezebite'] = { weapon = 'Great Sword', skill = 100 },
        ['Frostbite'] = { weapon = 'Great Sword', skill = 70 },
        ['Full Break'] = { weapon = 'Great Axe', skill = 225 },
        ['Full Swing'] = { weapon = 'Staff', skill = 200 },
        ['Gale Axe'] = { weapon = 'Axe', skill = 70 },
        ['Gate of Tartarus'] = { weapon = 'Staff', skill = 0, relic = true },
        ['Geirskogul'] = { weapon = 'Polearm', skill = 0, relic = true },
        ['Ground Strike'] = { weapon = 'Great Sword', skill = 250 },
        ['Guillotine'] = { weapon = 'Scythe', skill = 200 },
        ['Gust Slash'] = { weapon = 'Dagger', skill = 40 },
        ['Hard Slash'] = { weapon = 'Great Sword', skill = 5 },
        ['Heavy Shot'] = { weapon = 'Marksmanship', skill = 225 },
        ['Heavy Swing'] = { weapon = 'Staff', skill = 5 },
        ['Hexa Strike'] = { weapon = 'Club', skill = 220 },
        ['Hot Shot'] = { weapon = 'Marksmanship', skill = 5 },
        ['Howling Fist'] = { weapon = 'Hand-to-Hand', skill = 200 },
        ['Impulse Drive'] = { weapon = 'Polearm', skill = 240 },
        ['Iron Tempest'] = { weapon = 'Great Axe', skill = 40 },
        ['Judgment'] = { weapon = 'Club', skill = 200 },
        ['Keen Edge'] = { weapon = 'Great Axe', skill = 150 },
        ['Knights of Round'] = { weapon = 'Sword', skill = 0, relic = true },
        ['Leg Sweep'] = { weapon = 'Polearm', skill = 100 },
        ['Mercy Stroke'] = { weapon = 'Dagger', skill = 0, relic = true },
        ['Metatron Torment'] = { weapon = 'Great Axe', skill = 0, relic = true },
        ['Mistral Axe'] = { weapon = 'Axe', skill = 225 },
        ['Moonlight'] = { weapon = 'Club', skill = 125 },
        ['Namas Arrow'] = { weapon = 'Archery', skill = 0, relic = true },
        ['Nightmare Scythe'] = { weapon = 'Scythe', skill = 100 },
        ['One Inch Punch'] = { weapon = 'Hand-to-Hand', skill = 75 },
        ['Onslaught'] = { weapon = 'Axe', skill = 0, relic = true },
        ['Penta Thrust'] = { weapon = 'Polearm', skill = 150 },
        ['Piercing Arrow'] = { weapon = 'Archery', skill = 40 },
        ['Power Slash'] = { weapon = 'Great Sword', skill = 30 },
        ['Raging Axe'] = { weapon = 'Axe', skill = 5 },
        ['Raging Fists'] = { weapon = 'Hand-to-Hand', skill = 125 },
        ['Raging Rush'] = { weapon = 'Great Axe', skill = 200 },
        ['Raiden Thrust'] = { weapon = 'Polearm', skill = 70 },
        ['Rampage'] = { weapon = 'Axe', skill = 175 },
        ['Randgrith'] = { weapon = 'Club', skill = 0, relic = true },
        ['Red Lotus Blade'] = { weapon = 'Sword', skill = 50 },
        ['Retribution'] = { weapon = 'Staff', skill = 230 },
        ['Rock Crusher'] = { weapon = 'Staff', skill = 40 },
        ['Savage Blade'] = { weapon = 'Sword', skill = 240 },
        ['Scourge'] = { weapon = 'Great Sword', skill = 0, relic = true },
        ['Seraph Blade'] = { weapon = 'Sword', skill = 125 },
        ['Seraph Strike'] = { weapon = 'Club', skill = 100 },
        ['Shadow of Death'] = { weapon = 'Scythe', skill = 70 },
        ['Shadowstitch'] = { weapon = 'Dagger', skill = 70 },
        ['Shark Bite'] = { weapon = 'Dagger', skill = 225 },
        ['Shell Crusher'] = { weapon = 'Staff', skill = 175 },
        ['Shield Break'] = { weapon = 'Great Axe', skill = 5 },
        ['Shining Blade'] = { weapon = 'Sword', skill = 100 },
        ['Shining Strike'] = { weapon = 'Club', skill = 5 },
        ['Shockwave'] = { weapon = 'Great Sword', skill = 150 },
        ['Shoulder Tackle'] = { weapon = 'Hand-to-Hand', skill = 40 },
        ['Sickle Moon'] = { weapon = 'Great Sword', skill = 200 },
        ['Sidewinder'] = { weapon = 'Archery', skill = 175 },
        ['Skewer'] = { weapon = 'Polearm', skill = 200 },
        ['Skullbreaker'] = { weapon = 'Club', skill = 150 },
        ['Slice'] = { weapon = 'Scythe', skill = 5 },
        ['Slug Shot'] = { weapon = 'Marksmanship', skill = 175 },
        ['Smash Axe'] = { weapon = 'Axe', skill = 40 },
        ['Sniper Shot'] = { weapon = 'Marksmanship', skill = 80 },
        ['Spinning Attack'] = { weapon = 'Hand-to-Hand', skill = 150 },
        ['Spinning Axe'] = { weapon = 'Axe', skill = 150 },
        ['Spinning Scythe'] = { weapon = 'Scythe', skill = 125 },
        ['Spinning Slash'] = { weapon = 'Great Sword', skill = 225 },
        ['Spiral Hell'] = { weapon = 'Scythe', skill = 240 },
        ['Spirit Taker'] = { weapon = 'Staff', skill = 215 },
        ['Spirits Within'] = { weapon = 'Sword', skill = 175 },
        ['Split Shot'] = { weapon = 'Marksmanship', skill = 40 },
        ['Starburst'] = { weapon = 'Staff', skill = 100 },
        ['Starlight'] = { weapon = 'Club', skill = 40 },
        ['Steel Cyclone'] = { weapon = 'Great Axe', skill = 240 },
        ['Sturmwind'] = { weapon = 'Great Axe', skill = 70 },
        ['Sunburst'] = { weapon = 'Staff', skill = 150 },
        ['Swift Blade'] = { weapon = 'Sword', skill = 225 },
        ['Tachi: Enpi'] = { weapon = 'Great Katana', skill = 5 },
        ['Tachi: Gekko'] = { weapon = 'Great Katana', skill = 225 },
        ['Tachi: Goten'] = { weapon = 'Great Katana', skill = 70 },
        ['Tachi: Hobaku'] = { weapon = 'Great Katana', skill = 30 },
        ['Tachi: Jinpu'] = { weapon = 'Great Katana', skill = 150 },
        ['Tachi: Kagero'] = { weapon = 'Great Katana', skill = 100 },
        ['Tachi: Kaiten'] = { weapon = 'Great Katana', skill = 0, relic = true },
        ['Tachi: Kasha'] = { weapon = 'Great Katana', skill = 250 },
        ['Tachi: Koki'] = { weapon = 'Great Katana', skill = 175 },
        ['Tachi: Yukikaze'] = { weapon = 'Great Katana', skill = 200 },
        ['Thunder Thrust'] = { weapon = 'Polearm', skill = 30 },
        ['True Strike'] = { weapon = 'Club', skill = 175 },
        ['Viper Bite'] = { weapon = 'Dagger', skill = 100 },
        ['Vorpal Blade'] = { weapon = 'Sword', skill = 200 },
        ['Vorpal Scythe'] = { weapon = 'Scythe', skill = 150 },
        ['Vorpal Thrust'] = { weapon = 'Polearm', skill = 175 },
        ['Wasp Sting'] = { weapon = 'Dagger', skill = 5 },
        ['Weapon Break'] = { weapon = 'Great Axe', skill = 175 },
        ['Wheeling Thrust'] = { weapon = 'Polearm', skill = 225 },
    },
};

M.horizon = {
    abilitiesByName = {
        ['Accomplice'] = { job = 6, level = 45 },
        ['Aggressor'] = { job = 1, level = 45 },
        ['Ancient Circle'] = { job = 14, level = 5 },
        ['Arcane Circle'] = { job = 8, level = 5 },
        ['Astral Flow'] = { job = 15, level = 1 },
        ['Barrage'] = { job = 11, level = 30 },
        ['Benediction'] = { job = 3, level = 1 },
        ['Berserk'] = { job = 1, level = 15 },
        ['Blood Weapon'] = { job = 8, level = 1 },
        ['Boost'] = { job = 2, level = 5 },
        ['Bully'] = { job = 6, level = 40 },
        ['Call Beast'] = { job = 9, level = 23 },
        ['Call Wyvern'] = { job = 14, level = 1 },
        ['Camouflage'] = { job = 11, level = 20 },
        ['Chainspell'] = { job = 5, level = 1 },
        ['Chakra'] = { job = 2, level = 35 },
        ['Charm'] = { job = 9, level = 1 },
        ['Chi Blast'] = { job = 2, level = 41 },
        ['Chivalry'] = { job = 7, level = 45 },
        ['Collaborator'] = { job = 6, level = 45 },
        ['Convert'] = { job = 5, level = 40 },
        ['Counterstance'] = { job = 2, level = 45 },
        ['Cover'] = { job = 7, level = 35 },
        ['Defender'] = { job = 1, level = 25 },
        ['Devotion'] = { job = 3, level = 45 },
        ['Divine Seal'] = { job = 3, level = 15 },
        ['Dodge'] = { job = 2, level = 25 },
        ['Eagle Eye Shot'] = { job = 11, level = 1 },
        ['Elemental Seal'] = { job = 4, level = 15 },
        ['Familiar'] = { job = 9, level = 1 },
        ['Fight'] = { job = 9, level = 1, pet = true },
        ['Flee'] = { job = 6, level = 25 },
        ['Focus'] = { job = 2, level = 15 },
        ['Gauge'] = { job = 9, level = 10 },
        ['Hasso'] = { job = 12, level = 25 },
        ['Heel'] = { job = 9, level = 10, pet = true },
        ['Hide'] = { job = 6, level = 45 },
        ['High Jump'] = { job = 14, level = 35 },
        ['Holy Circle'] = { job = 7, level = 5 },
        ['Hundred Fists'] = { job = 2, level = 1 },
        ['Invincible'] = { job = 7, level = 1 },
        ['Jump'] = { job = 14, level = 10 },
        ['Last Resort'] = { job = 8, level = 15 },
        ['Leave'] = { job = 9, level = 35, pet = true },
        ['Manafont'] = { job = 4, level = 1 },
        ['Meditate'] = { job = 12, level = 30 },
        ['Meikyo Shisui'] = { job = 12, level = 1 },
        ['Mighty Strikes'] = { job = 1, level = 1 },
        ['Mikage'] = { job = 13, level = 1 },
        ['Mug'] = { job = 6, level = 35 },
        ['Perfect Dodge'] = { job = 6, level = 1 },
        ['Provoke'] = { job = 1, level = 5 },
        ['Rampart'] = { job = 7, level = 62 },
        ['Ready'] = { job = 9, level = 25, pet = true },
        ['Reward'] = { job = 9, level = 12 },
        ['Scavenge'] = { job = 11, level = 10 },
        ['Seigan'] = { job = 12, level = 35 },
        ['Sentinel'] = { job = 7, level = 30 },
        ['Shadowbind'] = { job = 11, level = 40 },
        ['Sharpshot'] = { job = 11, level = 1 },
        ['Shield Bash'] = { job = 7, level = 15 },
        ['Sic'] = { job = 9, level = 25, pet = true },
        ['Sneak Attack'] = { job = 6, level = 15 },
        ['Soul Voice'] = { job = 10, level = 1 },
        ['Souleater'] = { job = 8, level = 30 },
        ['Spirit Link'] = { job = 14, level = 25 },
        ['Spirit Surge'] = { job = 14, level = 1 },
        ['Stay'] = { job = 9, level = 15, pet = true },
        ['Steady Wing'] = { job = 14, level = 30 },
        ['Steal'] = { job = 6, level = 5 },
        ['Super Jump'] = { job = 14, level = 50 },
        ['Tame'] = { job = 9, level = 30 },
        ['Third Eye'] = { job = 12, level = 15 },
        ['Trick Attack'] = { job = 6, level = 30 },
        ['Unlimited Shot'] = { job = 11, level = 51 },
        ['Velocity Shot'] = { job = 11, level = 45 },
        ['Warcry'] = { job = 1, level = 35 },
        ['Warding Circle'] = { job = 12, level = 5 },
        ['Weapon Bash'] = { job = 8, level = 20 },
        ['Yonin'] = { job = 13, level = 20 },
    },
    retailOnlyAbilities = {
        ['Bestial Loyalty'] = true,
        ['Feral Howl'] = true,
        ['Killer Instinct'] = true,
        ['Run Wild'] = true,
        ['Snarl'] = true,
        ['Spur'] = true,
        ['Unleash'] = true,
    },
    spellOmissions = {
        ['Absorb-ACC'] = true,
        ['Absorb-Attri'] = true,
        ['Absorb-TP'] = true,
        ['Addle'] = true,
        ['Addle II'] = true,
        ['Adloquium'] = true,
        ['Adventurer\'s Dirge'] = true,
        ['Aera'] = true,
        ['Aera II'] = true,
        ['Aera III'] = true,
        ['Aero V'] = true,
        ['Aero VI'] = true,
        ['Aeroga IV'] = true,
        ['Aeroga V'] = true,
        ['Aeroja'] = true,
        ['Aisha: Ichi'] = true,
        ['Alexander'] = true,
        ['Anemohelix'] = true,
        ['Anemohelix II'] = true,
        ['Animus Augeo'] = true,
        ['Animus Minuo'] = true,
        ['Arise'] = true,
        ['Army\'s Paeon VI'] = true,
        ['Army\'s Paeon VII'] = true,
        ['Army\'s Paeon VIII'] = true,
        ['Aspir II'] = true,
        ['Aspir III'] = true,
        ['Atomos'] = true,
        ['Aurorastorm'] = true,
        ['Aurorastorm II'] = true,
        ['Auspice'] = true,
        ['Banish IV'] = true,
        ['Banish V'] = true,
        ['Banishga III'] = true,
        ['Banishga IV'] = true,
        ['Banishga V'] = true,
        ['Baramnesia'] = true,
        ['Baramnesra'] = true,
        ['Bindga'] = true,
        ['Bio III'] = true,
        ['Bio IV'] = true,
        ['Bio V'] = true,
        ['Blind II'] = true,
        ['Blindga'] = true,
        ['Blizzaga IV'] = true,
        ['Blizzaga V'] = true,
        ['Blizzaja'] = true,
        ['Blizzara'] = true,
        ['Blizzara II'] = true,
        ['Blizzara III'] = true,
        ['Blizzard V'] = true,
        ['Blizzard VI'] = true,
        ['Boost-AGI'] = true,
        ['Boost-CHR'] = true,
        ['Boost-DEX'] = true,
        ['Boost-INT'] = true,
        ['Boost-MND'] = true,
        ['Boost-STR'] = true,
        ['Boost-VIT'] = true,
        ['Break'] = true,
        ['Breakga'] = true,
        ['Burst II'] = true,
        ['Cactuar Fugue'] = true,
        ['Cait Sith'] = true,
        ['Chocobo Hum'] = true,
        ['Comet'] = true,
        ['Crusade'] = true,
        ['Cryohelix'] = true,
        ['Cryohelix II'] = true,
        ['Cura'] = true,
        ['Cura II'] = true,
        ['Cura III'] = true,
        ['Curaga V'] = true,
        ['Cure VI'] = true,
        ['Curse'] = true,
        ['Dark Carol II'] = true,
        ['Dark Threnody II'] = true,
        ['Death'] = true,
        ['Devotee Serenade'] = true,
        ['Dia III'] = true,
        ['Dia IV'] = true,
        ['Dia V'] = true,
        ['Diaga II'] = true,
        ['Diaga III'] = true,
        ['Diaga IV'] = true,
        ['Diaga V'] = true,
        ['Dispelga'] = true,
        ['Distract'] = true,
        ['Distract II'] = true,
        ['Distract III'] = true,
        ['Dokumori: Ni'] = true,
        ['Dokumori: San'] = true,
        ['Doton: San'] = true,
        ['Drain II'] = true,
        ['Drain III'] = true,
        ['Dread Spikes'] = true,
        ['Earth Carol II'] = true,
        ['Earth Threnody II'] = true,
        ['Embrava'] = true,
        ['Enaero'] = true,
        ['Enaero II'] = true,
        ['Enblizzard'] = true,
        ['Enblizzard II'] = true,
        ['Endark'] = true,
        ['Endark II'] = true,
        ['Enfire'] = true,
        ['Enfire II'] = true,
        ['Enlight II'] = true,
        ['Enstone'] = true,
        ['Enstone II'] = true,
        ['Enthunder'] = true,
        ['Enthunder II'] = true,
        ['Enwater'] = true,
        ['Enwater II'] = true,
        ['Esuna'] = true,
        ['Fira'] = true,
        ['Fira II'] = true,
        ['Fira III'] = true,
        ['Firaga IV'] = true,
        ['Firaga V'] = true,
        ['Firaja'] = true,
        ['Fire Carol II'] = true,
        ['Fire Threnody II'] = true,
        ['Fire V'] = true,
        ['Fire VI'] = true,
        ['Firestorm'] = true,
        ['Firestorm II'] = true,
        ['Flare II'] = true,
        ['Flood II'] = true,
        ['Flurry'] = true,
        ['Flurry II'] = true,
        ['Foe Lullaby II'] = true,
        ['Foe Requiem VII'] = true,
        ['Foe Requiem VIII'] = true,
        ['Foe Sirvente'] = true,
        ['Foil'] = true,
        ['Frazzle'] = true,
        ['Frazzle II'] = true,
        ['Frazzle III'] = true,
        ['Freeze II'] = true,
        ['Full Cure'] = true,
        ['Gain-AGI'] = true,
        ['Gain-CHR'] = true,
        ['Gain-DEX'] = true,
        ['Gain-INT'] = true,
        ['Gain-MND'] = true,
        ['Gain-STR'] = true,
        ['Gain-VIT'] = true,
        ['Gekka: Ichi'] = true,
        ['Geohelix'] = true,
        ['Geohelix II'] = true,
        ['Graviga'] = true,
        ['Gravity II'] = true,
        ['Hailstorm'] = true,
        ['Hailstorm II'] = true,
        ['Haste II'] = true,
        ['Hastega'] = true,
        ['Hojo: San'] = true,
        ['Holy II'] = true,
        ['Honor March'] = true,
        ['Horde Lullaby II'] = true,
        ['Huton: San'] = true,
        ['Hydrohelix'] = true,
        ['Hydrohelix II'] = true,
        ['Hyoton: San'] = true,
        ['Ice Carol II'] = true,
        ['Ice Threnody II'] = true,
        ['Impact'] = true,
        ['Inundation'] = true,
        ['Ionohelix'] = true,
        ['Ionohelix II'] = true,
        ['Jester\'s Operetta'] = true,
        ['Jubaku: Ni'] = true,
        ['Jubaku: San'] = true,
        ['Kakka: Ichi'] = true,
        ['Katon: San'] = true,
        ['Kaustra'] = true,
        ['Klimaform'] = true,
        ['Knight\'s Minne V'] = true,
        ['Kurayami: San'] = true,
        ['Light Carol II'] = true,
        ['Light Threnody II'] = true,
        ['Lightning Carol II'] = true,
        ['Ltng. Threnody II'] = true,
        ['Luminohelix'] = true,
        ['Luminohelix II'] = true,
        ['Mage\'s Ballad III'] = true,
        ['Massacre Elegy'] = true,
        ['Meteor'] = true,
        ['Meteor II'] = true,
        ['Migawari: Ichi'] = true,
        ['Monomi: Ichi'] = true,
        ['Myoshu: Ichi'] = true,
        ['Noctohelix'] = true,
        ['Noctohelix II'] = true,
        ['Odin'] = true,
        ['Paralyga'] = true,
        ['Paralyze II'] = true,
        ['Phalanx'] = true,
        ['Phalanx II'] = true,
        ['Pining Nocturne'] = true,
        ['Poison III'] = true,
        ['Poison IV'] = true,
        ['Poison V'] = true,
        ['Poisonga II'] = true,
        ['Poisonga III'] = true,
        ['Poisonga IV'] = true,
        ['Poisonga V'] = true,
        ['Protect V'] = true,
        ['Protected Aria'] = true,
        ['Pyrohelix'] = true,
        ['Pyrohelix II'] = true,
        ['Quake II'] = true,
        ['Rainstorm'] = true,
        ['Rainstorm II'] = true,
        ['Raiton: San'] = true,
        ['Raptor Mazurka'] = true,
        ['Recall-Jugner'] = true,
        ['Recall-Meriph'] = true,
        ['Recall-Pashh'] = true,
        ['Refresh II'] = true,
        ['Refresh III'] = true,
        ['Regen IV'] = true,
        ['Regen V'] = true,
        ['Repose'] = true,
        ['Reprisal'] = true,
        ['Reraise IV'] = true,
        ['Retrace'] = true,
        ['Sacrifice'] = true,
        ['Sandstorm'] = true,
        ['Sandstorm II'] = true,
        ['Sentinel\'s Scherzo'] = true,
        ['Shell V'] = true,
        ['Silencega'] = true,
        ['Siren'] = true,
        ['Slow II'] = true,
        ['Slowga'] = true,
        ['Stone V'] = true,
        ['Stone VI'] = true,
        ['Stonega IV'] = true,
        ['Stonega V'] = true,
        ['Stoneja'] = true,
        ['Stonera'] = true,
        ['Stonera II'] = true,
        ['Stonera III'] = true,
        ['Suiton: San'] = true,
        ['Temper'] = true,
        ['Temper II'] = true,
        ['Thundaga IV'] = true,
        ['Thundaga V'] = true,
        ['Thundaja'] = true,
        ['Thundara'] = true,
        ['Thundara II'] = true,
        ['Thundara III'] = true,
        ['Thunder V'] = true,
        ['Thunder VI'] = true,
        ['Thunderstorm'] = true,
        ['Thunderstorm II'] = true,
        ['Tornado II'] = true,
        ['Tractor II'] = true,
        ['Utsusemi: San'] = true,
        ['Valor Minuet V'] = true,
        ['Virus'] = true,
        ['Voidstorm'] = true,
        ['Voidstorm II'] = true,
        ['Water Carol II'] = true,
        ['Water Threnody II'] = true,
        ['Water V'] = true,
        ['Water VI'] = true,
        ['Watera'] = true,
        ['Watera II'] = true,
        ['Watera III'] = true,
        ['Waterga IV'] = true,
        ['Waterga V'] = true,
        ['Waterja'] = true,
        ['Wind Carol II'] = true,
        ['Wind Threnody II'] = true,
        ['Windstorm'] = true,
        ['Windstorm II'] = true,
        ['Yain: Ichi'] = true,
        ['Yurin: Ichi'] = true,
    },
    weaponskillsByName = {
        ['Arching Arrow'] = { weapon = 'Archery', skill = 225 },
        ['Armor Break'] = { weapon = 'Great Axe', skill = 100 },
        ['Asuran Fists'] = { weapon = 'Hand-to-Hand', skill = 250 },
        ['Avalanche Axe'] = { weapon = 'Axe', skill = 100 },
        ['Backhand Blow'] = { weapon = 'Hand-to-Hand', skill = 100 },
        ['Black Halo'] = { weapon = 'Club', skill = 230 },
        ['Blade: Chi'] = { weapon = 'Katana', skill = 150 },
        ['Blade: Ei'] = { weapon = 'Katana', skill = 175 },
        ['Blade: Jin'] = { weapon = 'Katana', skill = 200 },
        ['Blade: Ku'] = { weapon = 'Katana', skill = 250 },
        ['Blade: Metsu'] = { weapon = 'Katana', skill = 0, relic = true },
        ['Blade: Retsu'] = { weapon = 'Katana', skill = 30 },
        ['Blade: Rin'] = { weapon = 'Katana', skill = 5 },
        ['Blade: Teki'] = { weapon = 'Katana', skill = 70 },
        ['Blade: Ten'] = { weapon = 'Katana', skill = 225 },
        ['Blade: To'] = { weapon = 'Katana', skill = 100 },
        ['Blast Arrow'] = { weapon = 'Archery', skill = 200 },
        ['Blast Shot'] = { weapon = 'Marksmanship', skill = 200 },
        ['Brainshaker'] = { weapon = 'Club', skill = 70 },
        ['Burning Blade'] = { weapon = 'Sword', skill = 30 },
        ['Calamity'] = { weapon = 'Axe', skill = 200 },
        ['Catastrophe'] = { weapon = 'Scythe', skill = 0, relic = true },
        ['Circle Blade'] = { weapon = 'Sword', skill = 150 },
        ['Combo'] = { weapon = 'Hand-to-Hand', skill = 5 },
        ['Coronach'] = { weapon = 'Marksmanship', skill = 0, relic = true },
        ['Crescent Moon'] = { weapon = 'Great Sword', skill = 175 },
        ['Cross Reaper'] = { weapon = 'Scythe', skill = 225 },
        ['Cyclone'] = { weapon = 'Dagger', skill = 125 },
        ['Dancing Edge'] = { weapon = 'Dagger', skill = 200 },
        ['Dark Harvest'] = { weapon = 'Scythe', skill = 30 },
        ['Decimation'] = { weapon = 'Axe', skill = 240 },
        ['Detonator'] = { weapon = 'Marksmanship', skill = 250 },
        ['Double Thrust'] = { weapon = 'Polearm', skill = 5 },
        ['Dragon Kick'] = { weapon = 'Hand-to-Hand', skill = 225 },
        ['Dulling Arrow'] = { weapon = 'Archery', skill = 80 },
        ['Earth Crusher'] = { weapon = 'Staff', skill = 70 },
        ['Empyreal Arrow'] = { weapon = 'Archery', skill = 250 },
        ['Energy Drain'] = { weapon = 'Dagger', skill = 175 },
        ['Energy Steal'] = { weapon = 'Dagger', skill = 150 },
        ['Evisceration'] = { weapon = 'Dagger', skill = 230 },
        ['Fast Blade'] = { weapon = 'Sword', skill = 5 },
        ['Final Heaven'] = { weapon = 'Hand-to-Hand', skill = 0, relic = true },
        ['Flaming Arrow'] = { weapon = 'Archery', skill = 5 },
        ['Flat Blade'] = { weapon = 'Sword', skill = 75 },
        ['Freezebite'] = { weapon = 'Great Sword', skill = 100 },
        ['Frostbite'] = { weapon = 'Great Sword', skill = 70 },
        ['Full Break'] = { weapon = 'Great Axe', skill = 225 },
        ['Full Swing'] = { weapon = 'Staff', skill = 200 },
        ['Gale Axe'] = { weapon = 'Axe', skill = 70 },
        ['Gate of Tartarus'] = { weapon = 'Staff', skill = 0, relic = true },
        ['Geirskogul'] = { weapon = 'Polearm', skill = 0, relic = true },
        ['Ground Strike'] = { weapon = 'Great Sword', skill = 250 },
        ['Guillotine'] = { weapon = 'Scythe', skill = 200 },
        ['Gust Slash'] = { weapon = 'Dagger', skill = 40 },
        ['Hard Slash'] = { weapon = 'Great Sword', skill = 5 },
        ['Heavy Shot'] = { weapon = 'Marksmanship', skill = 225 },
        ['Heavy Swing'] = { weapon = 'Staff', skill = 5 },
        ['Hexa Strike'] = { weapon = 'Club', skill = 220 },
        ['Hot Shot'] = { weapon = 'Marksmanship', skill = 5 },
        ['Howling Fist'] = { weapon = 'Hand-to-Hand', skill = 200 },
        ['Impulse Drive'] = { weapon = 'Polearm', skill = 240 },
        ['Iron Tempest'] = { weapon = 'Great Axe', skill = 40 },
        ['Judgment'] = { weapon = 'Club', skill = 200 },
        ['Keen Edge'] = { weapon = 'Great Axe', skill = 150 },
        ['Knights of Round'] = { weapon = 'Sword', skill = 0, relic = true },
        ['Leg Sweep'] = { weapon = 'Polearm', skill = 100 },
        ['Mercy Stroke'] = { weapon = 'Dagger', skill = 0, relic = true },
        ['Metatron Torment'] = { weapon = 'Great Axe', skill = 0, relic = true },
        ['Mistral Axe'] = { weapon = 'Axe', skill = 225 },
        ['Moonlight'] = { weapon = 'Club', skill = 125 },
        ['Namas Arrow'] = { weapon = 'Archery', skill = 0, relic = true },
        ['Nightmare Scythe'] = { weapon = 'Scythe', skill = 100 },
        ['One Inch Punch'] = { weapon = 'Hand-to-Hand', skill = 75 },
        ['Onslaught'] = { weapon = 'Axe', skill = 0, relic = true },
        ['Penta Thrust'] = { weapon = 'Polearm', skill = 150 },
        ['Piercing Arrow'] = { weapon = 'Archery', skill = 40 },
        ['Power Slash'] = { weapon = 'Great Sword', skill = 30 },
        ['Raging Axe'] = { weapon = 'Axe', skill = 5 },
        ['Raging Fists'] = { weapon = 'Hand-to-Hand', skill = 125 },
        ['Raging Rush'] = { weapon = 'Great Axe', skill = 200 },
        ['Raiden Thrust'] = { weapon = 'Polearm', skill = 70 },
        ['Rampage'] = { weapon = 'Axe', skill = 175 },
        ['Randgrith'] = { weapon = 'Club', skill = 0, relic = true },
        ['Red Lotus Blade'] = { weapon = 'Sword', skill = 50 },
        ['Retribution'] = { weapon = 'Staff', skill = 230 },
        ['Rock Crusher'] = { weapon = 'Staff', skill = 40 },
        ['Savage Blade'] = { weapon = 'Sword', skill = 240 },
        ['Scourge'] = { weapon = 'Great Sword', skill = 0, relic = true },
        ['Seraph Blade'] = { weapon = 'Sword', skill = 125 },
        ['Seraph Strike'] = { weapon = 'Club', skill = 100 },
        ['Shadow of Death'] = { weapon = 'Scythe', skill = 70 },
        ['Shadowstitch'] = { weapon = 'Dagger', skill = 70 },
        ['Shark Bite'] = { weapon = 'Dagger', skill = 225 },
        ['Shell Crusher'] = { weapon = 'Staff', skill = 175 },
        ['Shield Break'] = { weapon = 'Great Axe', skill = 5 },
        ['Shining Blade'] = { weapon = 'Sword', skill = 100 },
        ['Shining Strike'] = { weapon = 'Club', skill = 5 },
        ['Shockwave'] = { weapon = 'Great Sword', skill = 150 },
        ['Shoulder Tackle'] = { weapon = 'Hand-to-Hand', skill = 40 },
        ['Sickle Moon'] = { weapon = 'Great Sword', skill = 200 },
        ['Sidewinder'] = { weapon = 'Archery', skill = 175 },
        ['Skewer'] = { weapon = 'Polearm', skill = 200 },
        ['Skullbreaker'] = { weapon = 'Club', skill = 150 },
        ['Slice'] = { weapon = 'Scythe', skill = 5 },
        ['Slug Shot'] = { weapon = 'Marksmanship', skill = 175 },
        ['Smash Axe'] = { weapon = 'Axe', skill = 40 },
        ['Sniper Shot'] = { weapon = 'Marksmanship', skill = 80 },
        ['Spinning Attack'] = { weapon = 'Hand-to-Hand', skill = 150 },
        ['Spinning Axe'] = { weapon = 'Axe', skill = 150 },
        ['Spinning Scythe'] = { weapon = 'Scythe', skill = 125 },
        ['Spinning Slash'] = { weapon = 'Great Sword', skill = 225 },
        ['Spiral Hell'] = { weapon = 'Scythe', skill = 240 },
        ['Spirit Taker'] = { weapon = 'Staff', skill = 215 },
        ['Spirits Within'] = { weapon = 'Sword', skill = 175 },
        ['Split Shot'] = { weapon = 'Marksmanship', skill = 40 },
        ['Starburst'] = { weapon = 'Staff', skill = 100 },
        ['Starlight'] = { weapon = 'Club', skill = 40 },
        ['Steel Cyclone'] = { weapon = 'Great Axe', skill = 240 },
        ['Sturmwind'] = { weapon = 'Great Axe', skill = 70 },
        ['Sunburst'] = { weapon = 'Staff', skill = 150 },
        ['Swift Blade'] = { weapon = 'Sword', skill = 225 },
        ['Tachi: Enpi'] = { weapon = 'Great Katana', skill = 5 },
        ['Tachi: Gekko'] = { weapon = 'Great Katana', skill = 225 },
        ['Tachi: Goten'] = { weapon = 'Great Katana', skill = 70 },
        ['Tachi: Hobaku'] = { weapon = 'Great Katana', skill = 30 },
        ['Tachi: Jinpu'] = { weapon = 'Great Katana', skill = 150 },
        ['Tachi: Kagero'] = { weapon = 'Great Katana', skill = 100 },
        ['Tachi: Kaiten'] = { weapon = 'Great Katana', skill = 0, relic = true },
        ['Tachi: Kasha'] = { weapon = 'Great Katana', skill = 250 },
        ['Tachi: Koki'] = { weapon = 'Great Katana', skill = 175 },
        ['Tachi: Yukikaze'] = { weapon = 'Great Katana', skill = 200 },
        ['Thunder Thrust'] = { weapon = 'Polearm', skill = 30 },
        ['True Strike'] = { weapon = 'Club', skill = 175 },
        ['Viper Bite'] = { weapon = 'Dagger', skill = 100 },
        ['Vorpal Blade'] = { weapon = 'Sword', skill = 200 },
        ['Vorpal Scythe'] = { weapon = 'Scythe', skill = 150 },
        ['Vorpal Thrust'] = { weapon = 'Polearm', skill = 175 },
        ['Wasp Sting'] = { weapon = 'Dagger', skill = 5 },
        ['Weapon Break'] = { weapon = 'Great Axe', skill = 175 },
        ['Wheeling Thrust'] = { weapon = 'Polearm', skill = 225 },
    },
};

-- Blood pact name -> status effect ID for slot corner badges (ward buffs + rage debuffs).
M.bloodPactStatusEffects = {
    ['Rock Throw'] = 13,
    ['Rock Buster'] = 11,
    ['Megalith Throw'] = 13,
    ['Mountain Buster'] = 11,
    ['Geocrush'] = 10,
    ['Shock Strike'] = 10,
    ['Thunderspark'] = 4,
    ['Chaotic Strike'] = 10,
    ['Tail Whip'] = 21,
    ['Moonlit Charge'] = 5,
    ['Crescent Fang'] = 4,
    ['Poison Nails'] = 3,
    ['Diamond Storm'] = 148,
    ['Poison Ruby'] = 3,
    ['Shining Ruby'] = 41,
    ['Glittering Ruby'] = 308,
    ['Crimson Howl'] = 549,
    ['Frost Armor'] = 35,
    ['Sleepga'] = 2,
    ['Whispering Wind'] = 78,
    ['Hastega'] = 33,
    ['Aerial Armor'] = 36,
    ['Earthen Ward'] = 37,
    ['Rolling Thunder'] = 98,
    ['Lightning Armor'] = 38,
    ['Slowga'] = 13,
    ['Spring Water'] = 43,
    ['Ecliptic Growl'] = 515,
    ['Ecliptic Howl'] = 90,
    ['Lunar Cry'] = 146,
    ['Somnolence'] = 21,
    ['Nightmare'] = 2,
};

-- Weaponskill label tiers (quest / relic / mythic / empyrean / aeonic / prime).
-- Skill numbers for quest/aeonic come from weaponskillsByName when omitted here.
M.weaponskillTiers = {
    -- Quest-gated
    ['One Inch Punch'] = 'quest',
    ['Flat Blade'] = 'quest',
    ['Spirits Within'] = 'quest',
    ['Evisceration'] = 'quest',
    ['Savage Blade'] = 'quest',
    ['Steel Cyclone'] = 'quest',
    ['Spiral Hell'] = 'quest',
    ['Retribution'] = 'quest',
    ['Black Halo'] = 'quest',
    ['Decimation'] = 'quest',
    ['Impulse Drive'] = 'quest',
    ['Ground Strike'] = 'quest',
    ['Blade: Ku'] = 'quest',
    ['Tachi: Kasha'] = 'quest',
    ['Detonator'] = 'quest',
    ['Empyreal Arrow'] = 'quest',
    ['Asuran Fists'] = 'quest',
    -- Relic (also flagged relic=true on weaponskillsByName entries)
    ['Final Heaven'] = 'relic',
    ['Mercy Stroke'] = 'relic',
    ['Knights of Round'] = 'relic',
    ['Scourge'] = 'relic',
    ['Onslaught'] = 'relic',
    ['Metatron Torment'] = 'relic',
    ['Catastrophe'] = 'relic',
    ['Geirskogul'] = 'relic',
    ['Blade: Metsu'] = 'relic',
    ['Tachi: Kaiten'] = 'relic',
    ['Randgrith'] = 'relic',
    ['Gate of Tartarus'] = 'relic',
    ['Namas Arrow'] = 'relic',
    ['Coronach'] = 'relic',
    -- Mythic
    ["Ascetic's Fury"] = 'mythic',
    ['Stringing Pummel'] = 'mythic',
    ['Mandalic Stab'] = 'mythic',
    ['Atonement'] = 'mythic',
    ["King's Justice"] = 'mythic',
    ['Insurgency'] = 'mythic',
    ['Drakesbane'] = 'mythic',
    ['Blade: Kamu'] = 'mythic',
    ['Tachi: Rana'] = 'mythic',
    ['Flash Nova'] = 'mythic',
    ['Vidohunir'] = 'mythic',
    ['Refulgent Arrow'] = 'mythic',
    ['Trueflight'] = 'mythic',
    -- Empyrean
    ['Victory Smite'] = 'empyrean',
    ['Mordant Rime'] = 'empyrean',
    ['Expiacion'] = 'empyrean',
    ['Torcleaver'] = 'empyrean',
    ['Primal Rend'] = 'empyrean',
    ["Ukko's Fury"] = 'empyrean',
    ['Upheaval'] = 'empyrean',
    ['Quietus'] = 'empyrean',
    ["Camlann's Torment"] = 'empyrean',
    ['Blade: Hi'] = 'empyrean',
    ['Tachi: Fudo'] = 'empyrean',
    ['Realmrazer'] = 'empyrean',
    ['Garland of Bliss'] = 'empyrean',
    ["Jishnu's Radiance"] = 'empyrean',
    ['Leaden Salute'] = 'empyrean',
    -- Aeonic
    ['Shijin Spiral'] = { tier = 'aeonic', skill = 357 },
    ["Rudra's Storm"] = { tier = 'aeonic', skill = 357 },
    ['Resolution'] = { tier = 'aeonic', skill = 357 },
    ['Dimidiation'] = { tier = 'aeonic', skill = 357 },
    ['Ruinator'] = { tier = 'aeonic', skill = 357 },
    ['Cloudsplitter'] = { tier = 'aeonic', skill = 357 },
    ['Fell Cleave'] = { tier = 'aeonic', skill = 357 },
    ['Entropy'] = { tier = 'aeonic', skill = 357 },
    ['Stardiver'] = { tier = 'aeonic', skill = 357 },
    ['Blade: Shun'] = { tier = 'aeonic', skill = 357 },
    ['Tachi: Shoha'] = { tier = 'aeonic', skill = 357 },
    ['Exudation'] = { tier = 'aeonic', skill = 357 },
    ['Omniscience'] = { tier = 'aeonic', skill = 357 },
    ['Cataclysm'] = { tier = 'aeonic', skill = 357 },
    ['Apex Arrow'] = { tier = 'aeonic', skill = 357 },
    ['Wildfire'] = { tier = 'aeonic', skill = 357 },
    -- Prime
    ['Tornado Kick'] = 'prime',
    ['Pyrrhic Kleos'] = 'prime',
    ['Death Blossom'] = 'prime',
    ['Herculean Slash'] = 'prime',
    ['Bora Axe'] = 'prime',
    ['Infernal Scythe'] = 'prime',
    ['Sonic Thrust'] = 'prime',
    ['Blade: Yu'] = 'prime',
    ['Tachi: Ageha'] = 'prime',
    ['Shattersoul'] = 'prime',
    ['Numbing Shot'] = 'prime',
    ['Last Stand'] = 'prime',
    ['Exenterator'] = 'prime',
    ['Chant du Cygne'] = 'prime',
    ['Requiescat'] = 'prime',
};

return M;
