--[[
* Skillchain property data sourced from Chains addon skills.lua
* Retail: https://github.com/Chibloom/Sippius.s-Ashita-v4-addons/tree/main/chains
* Horizon: https://github.com/NerfOnline/Chains-Horizon/tree/main/chains
]]--
local M = {};
M.horizon = {
    weaponskills = {
        [1] = { en = 'Combo', props = { 'Impaction' } },
        [2] = { en = 'Shoulder Tackle', props = { 'Reverberation', 'Impaction' } },
        [3] = { en = 'One Inch Punch', props = { 'Compression' } },
        [4] = { en = 'Backhand Blow', props = { 'Detonation' } },
        [5] = { en = 'Raging Fists', props = { 'Impaction' } },
        [6] = { en = 'Spinning Attack', props = { 'Liquefaction', 'Impaction' } },
        [7] = { en = 'Howling Fist', props = { 'Transfixion', 'Impaction' } },
        [8] = { en = 'Dragon Kick', props = { 'Fragmentation' } },
        [9] = { en = 'Asuran Fists', props = { 'Gravitation', 'Liquefaction' } },
        [10] = { en = 'Final Heaven', props = { 'Light', 'Fusion' } },
        [16] = { en = 'Wasp Sting', props = { 'Scission' } },
        [17] = { en = 'Viper Bite', props = { 'Scission' } },
        [18] = { en = 'Shadowstitch', props = { 'Reverberation' } },
        [19] = { en = 'Gust Slash', props = { 'Detonation' } },
        [20] = { en = 'Cyclone', props = { 'Detonation', 'Impaction' } },
        [23] = { en = 'Dancing Edge', props = { 'Scission', 'Detonation' } },
        [24] = { en = 'Shark Bite', props = { 'Fragmentation' } },
        [25] = { en = 'Evisceration', props = { 'Gravitation', 'Transfixion' } },
        [26] = { en = 'Mercy Stroke', props = { 'Darkness', 'Gravitation' } },
        [32] = { en = 'Fast Blade', props = { 'Scission' } },
        [33] = { en = 'Burning Blade', props = { 'Liquefaction' } },
        [34] = { en = 'Red Lotus Blade', props = { 'Liquefaction', 'Detonation' } },
        [35] = { en = 'Flat Blade', props = { 'Impaction' } },
        [36] = { en = 'Shining Blade', props = { 'Scission' } },
        [37] = { en = 'Seraph Blade', props = { 'Scission', 'Transfixion' } },
        [38] = { en = 'Circle Blade', props = { 'Reverberation', 'Impaction' } },
        [40] = { en = 'Vorpal Blade', props = { 'Scission', 'Impaction' } },
        [41] = { en = 'Swift Blade', props = { 'Gravitation' } },
        [42] = { en = 'Savage Blade', props = { 'Fragmentation', 'Scission' } },
        [43] = { en = 'Knights of Round', props = { 'Light', 'Fusion' } },
        [48] = { en = 'Hard Slash', props = { 'Scission' } },
        [49] = { en = 'Power Slash', props = { 'Transfixion' } },
        [50] = { en = 'Frostbite', props = { 'Induration' } },
        [51] = { en = 'Freezebite', props = { 'Induration', 'Detonation' } },
        [52] = { en = 'Shockwave', props = { 'Reverberation' } },
        [53] = { en = 'Crescent Moon', props = { 'Scission', 'Compression' } },
        [54] = { en = 'Sickle Moon', props = { 'Scission', 'Reverberation' } },
        [55] = { en = 'Spinning Slash', props = { 'Fragmentation' } },
        [56] = { en = 'Ground Strike', props = { 'Fragmentation', 'Distortion' } },
        [57] = { en = 'Scourge', props = { 'Light', 'Fusion' } },
        [64] = { en = 'Raging Axe', props = { 'Detonation', 'Impaction' } },
        [65] = { en = 'Smash Axe', props = { 'Induration', 'Reverberation' } },
        [66] = { en = 'Gale Axe', props = { 'Detonation' } },
        [67] = { en = 'Avalanche Axe', props = { 'Induration' } },
        [68] = { en = 'Spinning Axe', props = { 'Liquefaction', 'Scission' } },
        [69] = { en = 'Rampage', props = { 'Scission' } },
        [70] = { en = 'Calamity', props = { 'Scission', 'Impaction' } },
        [71] = { en = 'Mistral Axe', props = { 'Fusion' } },
        [72] = { en = 'Decimation', props = { 'Fusion', 'Detonation' } },
        [73] = { en = 'Onslaught', props = { 'Darkness', 'Gravitation' } },
        [80] = { en = 'Shield Break', props = { 'Impaction' } },
        [81] = { en = 'Iron Tempest', props = { 'Scission' } },
        [82] = { en = 'Sturmwind', props = { 'Reverberation', 'Scission' } },
        [83] = { en = 'Armor Break', props = { 'Impaction' } },
        [84] = { en = 'Keen Edge', props = { 'Compression' } },
        [85] = { en = 'Weapon Break', props = { 'Impaction' } },
        [86] = { en = 'Raging Rush', props = { 'Induration', 'Reverberation' } },
        [87] = { en = 'Full Break', props = { 'Distortion' } },
        [88] = { en = 'Steel Cyclone', props = { 'Distortion', 'Detonation' } },
        [89] = { en = 'Metatron Torment', props = { 'Light', 'Fusion' } },
        [96] = { en = 'Slice', props = { 'Scission' } },
        [97] = { en = 'Dark Harvest', props = { 'Compression' } },
        [98] = { en = 'Shadow of Death', props = { 'Induration', 'Reverberation' } },
        [99] = { en = 'Nightmare Scythe', props = { 'Compression', 'Scission' } },
        [100] = { en = 'Spinning Scythe', props = { 'Reverberation', 'Scission' } },
        [101] = { en = 'Vorpal Scythe', props = { 'Transfixion', 'Scission' } },
        [102] = { en = 'Guillotine', props = { 'Induration' } },
        [103] = { en = 'Cross Reaper', props = { 'Distortion' } },
        [104] = { en = 'Spiral Hell', props = { 'Gravitation', 'Compression' } },
        [105] = { en = 'Catastrophe', props = { 'Darkness', 'Gravitation' } },
        [112] = { en = 'Double Thrust', props = { 'Transfixion' } },
        [113] = { en = 'Thunder Thrust', props = { 'Transfixion', 'Impaction' } },
        [114] = { en = 'Raiden Thrust', props = { 'Transfixion', 'Impaction' } },
        [115] = { en = 'Leg Sweep', props = { 'Impaction' } },
        [116] = { en = 'Penta Thrust', props = { 'Compression' } },
        [117] = { en = 'Vorpal Thrust', props = { 'Reverberation', 'Transfixion' } },
        [118] = { en = 'Skewer', props = { 'Transfixion', 'Induration' } },
        [119] = { en = 'Wheeling Thrust', props = { 'Fusion' } },
        [120] = { en = 'Impulse Drive', props = { 'Gravitation', 'Induration' } },
        [121] = { en = 'Geirskogul', props = { 'Light', 'Distortion' } },
        [128] = { en = 'Blade: Rin', props = { 'Transfixion' } },
        [129] = { en = 'Blade: Retsu', props = { 'Scission' } },
        [130] = { en = 'Blade: Teki', props = { 'Reverberation' } },
        [131] = { en = 'Blade: To', props = { 'Induration', 'Detonation' } },
        [132] = { en = 'Blade: Chi', props = { 'Transfixion', 'Impaction' } },
        [133] = { en = 'Blade: Ei', props = { 'Compression' } },
        [134] = { en = 'Blade: Jin', props = { 'Detonation', 'Impaction' } },
        [135] = { en = 'Blade: Ten', props = { 'Gravitation' } },
        [136] = { en = 'Blade: Ku', props = { 'Gravitation', 'Transfixion' } },
        [137] = { en = 'Blade: Metsu', props = { 'Darkness', 'Fragmentation' } },
        [144] = { en = 'Tachi: Enpi', props = { 'Transfixion', 'Scission' } },
        [145] = { en = 'Tachi: Hobaku', props = { 'Induration' } },
        [146] = { en = 'Tachi: Goten', props = { 'Transfixion', 'Impaction' } },
        [147] = { en = 'Tachi: Kagero', props = { 'Liquefaction' } },
        [148] = { en = 'Tachi: Jinpu', props = { 'Scission', 'Detonation' } },
        [149] = { en = 'Tachi: Koki', props = { 'Reverberation', 'Impaction' } },
        [150] = { en = 'Tachi: Yukikaze', props = { 'Induration', 'Detonation' } },
        [151] = { en = 'Tachi: Gekko', props = { 'Distortion', 'Reverberation' } },
        [152] = { en = 'Tachi: Kasha', props = { 'Fusion', 'Compression' } },
        [153] = { en = 'Tachi: Kaiten', props = { 'Light', 'Fragmentation' } },
        [160] = { en = 'Shining Strike', props = { 'Transfixion' } },
        [161] = { en = 'Seraph Strike', props = { 'Scission' } },
        [162] = { en = 'Brainshaker', props = { 'Reverberation' } },
        [165] = { en = 'Skullbreaker', props = { 'Induration', 'Reverberation' } },
        [166] = { en = 'True Strike', props = { 'Detonation', 'Impaction' } },
        [167] = { en = 'Judgment', props = { 'Impaction' } },
        [168] = { en = 'Hexa Strike', props = { 'Fusion' } },
        [169] = { en = 'Black Halo', props = { 'Fragmentation', 'Compression' } },
        [170] = { en = 'Randgrith', props = { 'Light', 'Fragmentation' } },
        [176] = { en = 'Heavy Swing', props = { 'Impaction' } },
        [177] = { en = 'Rock Crusher', props = { 'Impaction' } },
        [178] = { en = 'Earth Crusher', props = { 'Detonation', 'Impaction' } },
        [179] = { en = 'Starburst', props = { 'Compression', 'Transfixion' } },
        [180] = { en = 'Sunburst', props = { 'Transfixion', 'Reverberation' } },
        [181] = { en = 'Shell Crusher', props = { 'Detonation' } },
        [182] = { en = 'Full Swing', props = { 'Liquefaction', 'Impaction' } },
        [184] = { en = 'Retribution', props = { 'Gravitation', 'Reverberation' } },
        [185] = { en = 'Gate of Tartarus', props = { 'Darkness', 'Distortion' } },
        [192] = { en = 'Flaming Arrow', props = { 'Liquefaction', 'Transfixion' } },
        [193] = { en = 'Piercing Arrow', props = { 'Reverberation', 'Transfixion' } },
        [194] = { en = 'Dulling Arrow', props = { 'Liquefaction', 'Transfixion' } },
        [196] = { en = 'Sidewinder', props = { 'Reverberation', 'Transfixion', 'Detonation' } },
        [197] = { en = 'Blast Arrow', props = { 'Induration', 'Transfixion' } },
        [198] = { en = 'Arching Arrow', props = { 'Fusion' } },
        [199] = { en = 'Empyreal Arrow', props = { 'Fusion', 'Transfixion' } },
        [200] = { en = 'Namas Arrow', props = { 'Light', 'Distortion' } },
        [208] = { en = 'Hot Shot', props = { 'Liquefaction', 'Transfixion' } },
        [209] = { en = 'Split Shot', props = { 'Reverberation', 'Transfixion' } },
        [210] = { en = 'Sniper Shot', props = { 'Liquefaction', 'Transfixion' } },
        [212] = { en = 'Slug Shot', props = { 'Reverberation', 'Transfixion', 'Detonation' } },
        [213] = { en = 'Blast Shot', props = { 'Induration', 'Transfixion' } },
        [214] = { en = 'Heavy Shot', props = { 'Fusion' } },
        [215] = { en = 'Detonator', props = { 'Fusion', 'Transfixion' } },
        [216] = { en = 'Coronach', props = { 'Darkness', 'Fragmentation' } },
    },
    bloodPacts = {
        [513] = { en = 'Poison Nails', props = { 'Transfixion' } },
        [528] = { en = 'Moonlit Charge', props = { 'Compression' } },
        [529] = { en = 'Crescent Fang', props = { 'Transfixion' } },
        [544] = { en = 'Punch', props = { 'Liquefaction' } },
        [546] = { en = 'Burning Strike', props = { 'Impaction' } },
        [547] = { en = 'Double Punch', props = { 'Compression' } },
        [560] = { en = 'Rock Throw', props = { 'Scission' } },
        [562] = { en = 'Rock Buster', props = { 'Reverberation' } },
        [563] = { en = 'Megalith Throw', props = { 'Induration' } },
        [576] = { en = 'Barracuda Dive', props = { 'Reverberation' } },
        [578] = { en = 'Tail Whip', props = { 'Detonation' } },
        [592] = { en = 'Claw', props = { 'Detonation' } },
        [608] = { en = 'Axe Kick', props = { 'Induration' } },
        [612] = { en = 'Double Slap', props = { 'Scission' } },
        [624] = { en = 'Shock Strike', props = { 'Impaction' } },
    },
};
M.retail = {
    bloodPacts = {
        [513] = { en = 'Poison Nails', props = { 'Transfixion' } },
        [521] = { en = 'Regal Scratch', props = { 'Scission' } },
        [528] = { en = 'Moonlit Charge', props = { 'Compression' } },
        [529] = { en = 'Crescent Fang', props = { 'Transfixion' } },
        [534] = { en = 'Eclipse Bite', props = { 'Gravitation', 'Scission' } },
        [544] = { en = 'Punch', props = { 'Liquefaction' } },
        [546] = { en = 'Burning Strike', props = { 'Impaction' } },
        [547] = { en = 'Double Punch', props = { 'Compression' } },
        [550] = { en = 'Flaming Crush', props = { 'Fusion', 'Reverberation' } },
        [560] = { en = 'Rock Throw', props = { 'Scission' } },
        [562] = { en = 'Rock Buster', props = { 'Reverberation' } },
        [563] = { en = 'Megalith Throw', props = { 'Induration' } },
        [566] = { en = 'Mountain Buster', props = { 'Gravitation', 'Induration' } },
        [570] = { en = 'Crag Throw', props = { 'Gravitation', 'Scission' } },
        [576] = { en = 'Barracuda Dive', props = { 'Reverberation' } },
        [578] = { en = 'Tail Whip', props = { 'Detonation' } },
        [582] = { en = 'Spinning Dive', props = { 'Distortion', 'Detonation' } },
        [592] = { en = 'Claw', props = { 'Detonation' } },
        [598] = { en = 'Predator Claws', props = { 'Fragmentation', 'Scission' } },
        [608] = { en = 'Axe Kick', props = { 'Induration' } },
        [612] = { en = 'Double Slap', props = { 'Scission' } },
        [614] = { en = 'Rush', props = { 'Distortion', 'Scission' } },
        [624] = { en = 'Shock Strike', props = { 'Impaction' } },
        [630] = { en = 'Chaotic Strike', props = { 'Fragmentation', 'Transfixion' } },
        [634] = { en = 'Volt Strike', props = { 'Fragmentation', 'Scission' } },
        [656] = { en = 'Camisado', props = { 'Compression' } },
        [667] = { en = 'Blindside', props = { 'Gravitation', 'Transfixion' } },
        [672] = { en = 'Foot Kick', props = { 'Reverberation' } },
        [674] = { en = 'Whirl Claws', props = { 'Impaction' } },
        [675] = { en = 'Head Butt', props = { 'Detonation' } },
        [677] = { en = 'Wild Oats', props = { 'Transfixion' } },
        [678] = { en = 'Leaf Dagger', props = { 'Scission' } },
        [681] = { en = 'Razor Fang', props = { 'Impaction' } },
        [682] = { en = 'Claw Cyclone', props = { 'Scission' } },
        [683] = { en = 'Tail Blow', props = { 'Impaction' } },
        [685] = { en = 'Blockhead', props = { 'Reverberation' } },
        [686] = { en = 'Brain Crush', props = { 'Liquefaction' } },
        [689] = { en = 'Lamb Chop', props = { 'Impaction' } },
        [691] = { en = 'Sheep Charge', props = { 'Reverberation' } },
        [695] = { en = 'Big Scissors', props = { 'Scission' } },
        [698] = { en = 'Needleshot', props = { 'Transfixion' } },
        [699] = { en = '??? Needles', props = { 'Darkness', 'Fragmentation' } },
        [700] = { en = 'Frogkick', props = { 'Compression' } },
        [707] = { en = 'Power Attack', props = { 'Reverberation' } },
        [709] = { en = 'Rhino Attack', props = { 'Detonation' } },
        [717] = { en = 'Mandibular Bite', props = { 'Detonation' } },
        [723] = { en = 'Nimble Snap', props = { 'Impaction' } },
        [724] = { en = 'Cyclotail', props = { 'Impaction' } },
        [726] = { en = 'Double Claw', props = { 'Liquefaction' } },
        [727] = { en = 'Grapple', props = { 'Reverberation' } },
        [728] = { en = 'Spinning Top', props = { 'Impaction' } },
        [732] = { en = 'Suction', props = { 'Compression' } },
        [736] = { en = 'Sudden Lunge', props = { 'Impaction' } },
        [737] = { en = 'Spiral Spin', props = { 'Scission' } },
        [743] = { en = 'Scythe Tail', props = { 'Liquefaction' } },
        [744] = { en = 'Ripper Fang', props = { 'Induration' } },
        [745] = { en = 'Chomp Rush', props = { 'Darkness', 'Gravitation' } },
        [749] = { en = 'Back Heel', props = { 'Reverberation' } },
        [753] = { en = 'Tortoise Stomp', props = { 'Liquefaction' } },
        [756] = { en = 'Wing Slap', props = { 'Gravitation', 'Liquefaction' } },
        [757] = { en = 'Beak Lunge', props = { 'Scission' } },
        [759] = { en = 'Recoil Dive', props = { 'Transfixion' } },
        [761] = { en = 'Sensilla Blades', props = { 'Scission' } },
        [762] = { en = 'Tegmina Buffet', props = { 'Distortion', 'Detonation' } },
        [764] = { en = 'Swooping Frenzy', props = { 'Fusion', 'Reverberation' } },
        [765] = { en = 'Sweeping Gouge', props = { 'Induration' } },
        [767] = { en = 'Pentapeck', props = { 'Light', 'Distortion' } },
        [768] = { en = 'Tickling Tendrils', props = { 'Impaction' } },
        [772] = { en = 'Somersault', props = { 'Compression' } },
        [776] = { en = 'Pecking Flurry', props = { 'Transfixion' } },
        [777] = { en = 'Sickle Slash', props = { 'Transfixion' } },
        [780] = { en = 'Regal Gash', props = { 'Distortion', 'Detonation' } },
        [786] = { en = 'Disembowel', props = { 'Impaction' } },
        [787] = { en = 'Extirpating Salvo', props = { 'Fusion', 'Impaction' } },
        [789] = { en = 'Mega Scissors', props = { 'Gravitation', 'Scission' } },
        [791] = { en = 'Rhinowrecker', props = { 'Fusion', 'Transfixion' } },
        [792] = { en = 'Fluid Toss', props = { 'Reverberation' } },
        [793] = { en = 'Fluid Spread', props = { 'Fragmentation', 'Transfixion' } },
        [797] = { en = 'Hoof Volley', props = { 'Light', 'Fragmentation' } },
        [961] = { en = 'Welt', props = { 'Scission' } },
        [964] = { en = 'Roundhouse', props = { 'Detonation' } },
        [970] = { en = 'Hysteric Assault', props = { 'Fragmentation', 'Transfixion' } },
    },
};
return M;
